version: '2'
services:
  web:
    build: .
    command: apache2-foreground
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
    links:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"